#' Aggregate seasonal pixel indices to one lake-level index
#'
#' Summarizes the pixel-level seasonal index matrix of one lake and year into
#' lake-level statistics, including median, standard deviation, density-based
#' modal candidates, and a selected modal index value.
#'
#' @param seasonIndex A list created by [seasonal_index_per_pixel()] containing
#'   at least `RSindex`, `QualityThreshold`, `x`, `y`, `crs`, and `year`.
#' @param lakeName Optional character scalar with the lake name. If `NULL`, the
#'   output `Name` is `NA`.
#' @param lakeID Optional character scalar with a lake identifier. If `NULL`, an
#'   identifier is generated by [add_lakeID()] from mean coordinates.
#'
#' @return A list with index statistics (`IndexModusBest`, `IndexMedian`,
#'   `IndexSD`, `IndexModusPot`, `IndexDensity`, `IndexPixel`), metadata
#'   (`QualityThreshold`, `x`, `y`, `crs`, `year`), and lake identifiers (`Name`,
#'   `ID`).
#'
#' @details If more than one valid pixel is available, potential modes are
#'   detected from a kernel density estimate using `bw = "SJ"` and `adjust = 2`.
#'   Among sufficiently high local maxima, the mode with the highest density is
#'   selected as `IndexModusBest`. If exactly one valid pixel is available, that
#'   value is used for both median and mode.
#'
#' @importFrom stats density median sd
#' @export
seasonal_index_per_lake <- function(seasonIndex, lakeName = NULL, lakeID = NULL)
{
  mat <- seasonIndex$RSindex
  validPixel <- sum(!is.na(mat))
  
  output <- if(validPixel > 1){
    d <- stats::density(
      mat, 
      bw = "SJ", 
      adjust = 2, 
      na.rm = TRUE)
    peak_i <- which(diff(sign(diff(d$y))) == -2) 
    modus <- d$x[peak_i[d$y[peak_i] > 1.5 * mean(d$y)]]
    
    best_guess <- 
      if(length(modus) > 0L){
        x_modus <- which(d$x %in% modus)
        modus[order(d$y[x_modus], decreasing = TRUE)[1]]
      } else {
        NA
      }
    
    list("IndexModusBest" = best_guess,
         "IndexMedian" = median(mat, na.rm = TRUE),
         "IndexSD" = sd(mat, na.rm = TRUE),
         "IndexModusPot" = modus,
         "nValidPixel" = validPixel,
         "QualityThreshold" = seasonIndex$QualityThreshold,
         "IndexDensity" = d,
         "IndexPixel" = mat
    )
  } else if(validPixel == 1L){
    singleValue <- median(mat, na.rm = TRUE)
    list("IndexModusBest" = singleValue,
         "IndexMedian" = singleValue,
         "IndexSD" = NA,
         "IndexModusPot" = singleValue,
         "nValidPixel" = 1,
         "QualityThreshold" = seasonIndex$QualityThreshold,
         "IndexDensity" = NA,
         "IndexPixel" = mat
    )
  } else {
    list("IndexModusBest" = NA,
         "IndexMedian" = NA,
         "IndexSD" = NA,
         "IndexModusPot" = NA,
         "nValidPixel" = 0,
         "QualityThreshold" = seasonIndex$QualityThreshold,
         "IndexDensity" = NA,
         "IndexPixel" = NA
    )
  }
  
  output$x <- seasonIndex$x
  output$y <- seasonIndex$y
  output$crs <- seasonIndex$crs
  output$year <- seasonIndex$year
  
  add_lakeID(
    lakeIndex = output,
    lakeName = lakeName,
    lakeID = lakeID
  )
}

#' Add lake name and identifier to a lake index result
#'
#' Adds a human-readable lake name and a stable lake identifier to a list created
#' by [seasonal_index_per_lake()]. If no identifier is supplied, an identifier is
#' generated from the mean x and y coordinates of the lake grid.
#'
#' @param lakeIndex A list containing lake-level index results and at least the
#'   coordinate vectors `x` and `y`. Typically the list is produced internally by
#'   [seasonal_index_per_lake()].
#' @param lakeName Optional character scalar with the lake name. If `NULL`, the
#'   output element `Name` is set to `NA`.
#' @param lakeID Optional character scalar with a unique lake identifier. If
#'   `NULL`, the identifier is generated as `"<mean(x)>_<mean(y)>"`.
#'
#' @return The input list with two additional elements: `Name` and `ID`.
#'
#' @export
#' 
add_lakeID <- function(lakeIndex, lakeName = NULL, lakeID = NULL){
  if(is.null(lakeID)){
    lakeID <- paste0(mean(lakeIndex$x), "_", mean(lakeIndex$y))
  }
  if(is.null(lakeName)){
    lakeName <- NA
  }
  lakeIndex$Name <- lakeName
  lakeIndex$ID <- lakeID
  lakeIndex
}

